-- Database export: blog_new
-- Date: 2026-06-22 18:47:31
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `t_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类ID，自增主键',
  `name` varchar(50) NOT NULL COMMENT '分类名称',
  `slug` varchar(50) NOT NULL COMMENT 'URL 别名',
  `description` varchar(200) DEFAULT '' COMMENT '分类描述',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章分类表';

CREATE TABLE `t_post_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '文章ID，关联 t_post.id',
  `tag_id` bigint NOT NULL COMMENT '标签ID，关联 t_tag.id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_tag` (`post_id`,`tag_id`),
  KEY `idx_tag_id` (`tag_id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章-标签关联表';

CREATE TABLE `t_comment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '所属文章ID，关联 t_post.id',
  `parent_id` bigint DEFAULT NULL COMMENT '父评论ID，顶级评论为 NULL，关联 t_comment.id',
  `user_id` bigint DEFAULT NULL COMMENT '评论者用户ID（已登录），关联 t_user.id；匿名评论为 NULL',
  `nickname` varchar(50) DEFAULT '匿名' COMMENT '评论者昵称（未登录时使用）',
  `content` text NOT NULL COMMENT '评论正文内容',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '审核状态：0=待审核，1=已通过，2=已拒绝',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
  PRIMARY KEY (`id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_status` (`status`),
  KEY `idx_comment_post_status` (`post_id`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='评论表';

CREATE TABLE `t_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签ID，自增主键',
  `name` varchar(50) NOT NULL COMMENT '标签名称',
  `slug` varchar(50) NOT NULL COMMENT 'URL 别名',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章标签表';

CREATE TABLE `t_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID，自增主键',
  `username` varchar(50) NOT NULL COMMENT '登录用户名，唯一',
  `password` varchar(128) NOT NULL COMMENT '登录密码，MD5 加密存储',
  `nickname` varchar(50) DEFAULT '' COMMENT '用户昵称，用于前台展示',
  `email` varchar(100) DEFAULT '' COMMENT '电子邮箱',
  `avatar` varchar(500) DEFAULT '' COMMENT '头像 URL 地址',
  `bio` varchar(500) DEFAULT '' COMMENT '个人简介',
  `role` varchar(20) NOT NULL DEFAULT 'ROLE_USER' COMMENT '角色标识：ROLE_USER=普通用户，ROLE_ADMIN=管理员',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '账号状态：0=禁用，1=正常',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

CREATE TABLE `t_post_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '文章ID，关联 t_post.id',
  `category_id` bigint NOT NULL COMMENT '分类ID，关联 t_category.id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_category` (`post_id`,`category_id`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章-分类关联表';

CREATE TABLE `t_post` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文章ID，自增主键',
  `user_id` bigint NOT NULL COMMENT '作者ID，关联 t_user.id',
  `title` varchar(200) NOT NULL COMMENT '文章标题',
  `slug` varchar(200) NOT NULL COMMENT 'URL 别名，用于前台友好的访问地址',
  `summary` varchar(500) DEFAULT '' COMMENT '文章摘要，用于列表页展示',
  `content` mediumtext NOT NULL COMMENT '文章正文，Markdown 格式',
  `cover_image` varchar(500) DEFAULT '' COMMENT '封面图片 URL',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '发布状态：0=草稿，1=已发布，2=已下架',
  `is_top` tinyint NOT NULL DEFAULT '0' COMMENT '是否置顶：0=否，1=是',
  `allow_comment` tinyint NOT NULL DEFAULT '1' COMMENT '是否允许评论：0=否，1=是',
  `view_count` bigint NOT NULL DEFAULT '0' COMMENT '阅读量计数',
  `published_at` datetime DEFAULT NULL COMMENT '首次发布时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_slug` (`slug`),
  KEY `idx_post_list` (`status`,`is_top`,`published_at`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章表';

SET FOREIGN_KEY_CHECKS = 1;
