-- Database export: blog_new
-- Date: 2026-06-12 12:31:25
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `t_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类ID，自增主键',
  `name` varchar(50) NOT NULL COMMENT '分类名称',
  `slug` varchar(50) NOT NULL COMMENT 'URL 别名',
  `description` varchar(200) DEFAULT '' COMMENT '分类描述',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序值，越小越靠前',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章分类表';

INSERT INTO `t_category` (`id`, `name`, `slug`, `description`, `sort_order`, `created_at`) VALUES
('2', '后端', 'hou-duan', '记录后端技术栈相关文章', 1, '2026-06-11 13:26:44'),
('8', '前端', 'qian-duan', '测试测试', 0, '2026-06-12 11:00:51');

CREATE TABLE `t_comment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '所属文章ID，关联 t_post.id',
  `parent_id` bigint DEFAULT NULL COMMENT '父评论ID，顶级评论为 NULL，关联 t_comment.id',
  `user_id` bigint DEFAULT NULL COMMENT '评论者用户ID（已登录），关联 t_user.id；匿名评论为 NULL',
  `nickname` varchar(50) DEFAULT '匿名' COMMENT '评论者昵称（未登录时使用）',
  `content` text NOT NULL COMMENT '评论正文内容',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '审核状态：0=待审核，1=已通过，2=已拒绝',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
  PRIMARY KEY (`id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_status` (`status`),
  KEY `idx_comment_post_status` (`post_id`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='评论表';

INSERT INTO `t_comment` (`id`, `post_id`, `parent_id`, `user_id`, `nickname`, `content`, `status`, `created_at`) VALUES
('3', '2', NULL, '1', '超级管理员', '哈喽哈喽', 1, '2026-06-12 11:39:05'),
('4', '2', '3', '1', '超级管理员', '你好啊', 1, '2026-06-12 11:39:38'),
('5', '2', '4', '1', '超级管理员', '哈哈 你也好', 1, '2026-06-12 11:40:27'),
('6', '2', NULL, '1', '超级管理员', '嘻嘻', 1, '2026-06-12 11:52:18'),
('7', '2', '5', '1', '超级管理员', '你好我好 他也好', 1, '2026-06-12 11:57:22'),
('8', '2', '7', '1', '超级管理员', '哈哈哈', 1, '2026-06-12 11:59:03'),
('9', '2', '4', '1', '超级管理员', '我当然好啊', 1, '2026-06-12 12:01:39'),
('10', '2', '3', '1', '超级管理员', '草你妈', 2, '2026-06-12 12:02:03');

CREATE TABLE `t_post` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文章ID，自增主键',
  `user_id` bigint NOT NULL COMMENT '作者ID，关联 t_user.id',
  `title` varchar(200) NOT NULL COMMENT '文章标题',
  `slug` varchar(200) NOT NULL COMMENT 'URL 别名，用于前台友好的访问地址',
  `summary` varchar(500) DEFAULT '' COMMENT '文章摘要，用于列表页展示',
  `content` mediumtext NOT NULL COMMENT '文章正文，Markdown 格式',
  `cover_image` varchar(500) DEFAULT '' COMMENT '封面图片 URL',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '发布状态：0=草稿，1=已发布，2=已下架',
  `is_top` tinyint NOT NULL DEFAULT '0' COMMENT '是否置顶：0=否，1=是',
  `allow_comment` tinyint NOT NULL DEFAULT '1' COMMENT '是否允许评论：0=否，1=是',
  `view_count` bigint NOT NULL DEFAULT '0' COMMENT '阅读量计数',
  `published_at` datetime DEFAULT NULL COMMENT '首次发布时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_slug` (`slug`),
  KEY `idx_post_list` (`status`,`is_top`,`published_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章表';

INSERT INTO `t_post` (`id`, `user_id`, `title`, `slug`, `summary`, `content`, `cover_image`, `status`, `is_top`, `allow_comment`, `view_count`, `published_at`, `created_at`, `updated_at`) VALUES
('2', '1', 'Claude Fable 5', 'ce-shi', '', '大家好，我是程序员鱼皮。

就在刚刚，Anthropic 发布了新一代模型 **Claude Fable 5**，同时还放出了一个面向专业安全人员的「解限版」叫 Claude Mythos 5。

官方把它称为「神话级」模型，能力凌驾于之前的 Opus 系列之上。据说 Stripe 公司在自己 5000 万行的 Ruby 代码库里测了一圈，一天就搞定了团队原本要两个月才能完成的迁移工作。

这篇文章我会先带大家看看 Fable 5 到底更新了什么，然后上两轮硬核实测，分别让 Fable 5、Opus 4.8 和 GPT-5.5 同场竞技，看看新模型的 AI 编程能力到底怎么样。

友情提示，这次的测试成本有点高，希望大家心疼一下我的钱包，把这篇文章看到最后哦。

## **Claude Fable 5 更新了什么？**

### **1、一个模型，两个名字**

这次 Anthropic 同时放出了 Fable 5 和 Mythos 5，但它俩其实是 **同一个底层模型**，能力完全一样。区别只在「安全护栏」的松紧程度上。

Fable 5 面向所有人，今天就能用。但加了一层安全分类器，遇到涉及网络安全、生物化学或模型蒸馏（防止别人偷学能力去训练竞品）的请求时，会降级到 Opus 4.8 来回答你，并且给你一条提示。

Mythos 5 是把护栏拆掉的「完全体」，只发给 Anthropic 审核过的网络安全机构和少数生物研究人员，普通人接触不到。

关于 Fable 5 的降级机制，官方说平均不到 5% 的会话会触发。但我测试使用 Fable 5 来写文章的能力时，就触发了安全过滤，直接被切换到了 Opus 4.8。

不是哥们，写个文章哪里不安全了？！

肯定有朋友好奇，为什么这次更新不延续 Opus 系列，来个 Opus 4.9，而是直接跳到第 5 代？

因为它根本不是 Opus 这个级别的模型了，而是 Anthropic 内部一个更高的等级，叫 **Mythos 级**，能力直接碾压 Opus。

> 有趣的是，Fable（寓言）这个词本身就源自拉丁语 fabula，和希腊语的 Mythos（神话）是近亲。

简单来说，就是同一把刀，一把开了刃给专业人士，一把套了刀鞘发给大众。

### **2、定价全球最贵**

Claude Fable 5 和 Mythos 5 的定价是每百万输入 token 10 美元、输出 50 美元。

听起来你可能没什么感觉，但是对比一下目前主流模型的价格，你就知道有多离谱了：

**模型**

**输入 / 输出（每百万 token）**

**总成本**

DeepSeek V4

0.8

$1.2

Claude Opus 4.8

25

$30

GPT-5.5

30

$35

**Claude Fable 550$60**

Fable 5 的总成本直接是 Opus 4.8 的两倍、DeepSeek V4 的 50 倍，稳坐目前主流模型里最贵的位置。官方还特意强调了，这已经比之前的 Mythos Preview 便宜了一半多。

好家伙，便宜一半还是最贵的，以后的模型怕是普通人真的用不起了……

注意，官方说从今天到 6 月 22 号，Pro、Max、Team 这些套餐可以免费使用 Fable 5。但 **6 月 23 号之后就要单独花「用量积分」了**，等产能上来再恢复。所以想白嫖体验的，一定要利用好这两周的窗口期。

### **3、跑分炸裂**

每次新模型出来都得看看跑分。官方说 Fable 5 几乎在所有测试过的基准上都是 SOTA，尤其在编程、知识工作、视觉、科学研究这几个方向。而且 **任务越长、越复杂，它领先得越多**。

说实话我已经有点麻了，因为各家基本都说自己是 SOTA 最佳水平……

但这次 Fable 5 的成绩，确实配得上「炸裂」两个字。

挑几个亮眼的数据说说：

-   SWE-bench Pro（Agent 编程能力）是 80.3%，远超 GPT-5.5 的 58.6% 和 Opus 4.8 的 69.2%
    
-   FrontierCode（高质量编码）是 29.3%，Opus 4.8 只有 13.4%，GPT-5.5 是 5.7%
    
-   视觉能力（GDPpdf 文档推理）是 29.8%，GPT-5.5 是 24.9%，Opus 4.8 是 22.5%。官方让 Fable 5 去玩宝可梦火红版，纯视觉就通关了。
    

好家伙，这是断层式的提升啊！

不过跑分是一方面，好不好用还是得拿到真实项目里检验才知道。所以老规矩，我带大家动手测一测，拿 Fable 5、Opus 4.8 和 GPT-5.5 同场竞技。

正好 Cursor 第一时间就接入了 Fable 5，每次出新模型都能直接测试，方便得很。

我之前写过一套免费开源的 [《AI 编程零基础入门教程》](https://mp.weixin.qq.com/s?__biz=MzI1NDczNTAwMA==&mid=2247580489&idx=1&sn=ea128f6a8c5d79e641133615f85f7ab8&scene=21#wechat_redirect)，里面有 Cursor 的保姆级实战教程，感兴趣的同学可以看看。

接下来我准备了两轮实测。第一轮是让 3 个模型一把梭同一个全栈项目；第二轮更硬核，让它们重构 Claude Code 泄露的 50 多万行源码。

好了，我的钱包准备开始烧了。', '', 1, 0, 1, '33', '2026-06-11 14:43:26', '2026-06-11 14:43:12', '2026-06-12 12:25:05');

CREATE TABLE `t_post_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '文章ID，关联 t_post.id',
  `category_id` bigint NOT NULL COMMENT '分类ID，关联 t_category.id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_category` (`post_id`,`category_id`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章-分类关联表';

INSERT INTO `t_post_category` (`id`, `post_id`, `category_id`) VALUES
('20', '2', '2');

CREATE TABLE `t_post_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID，自增主键',
  `post_id` bigint NOT NULL COMMENT '文章ID，关联 t_post.id',
  `tag_id` bigint NOT NULL COMMENT '标签ID，关联 t_tag.id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_tag` (`post_id`,`tag_id`),
  KEY `idx_tag_id` (`tag_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章-标签关联表';

INSERT INTO `t_post_tag` (`id`, `post_id`, `tag_id`) VALUES
('20', '2', '4');

CREATE TABLE `t_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签ID，自增主键',
  `name` varchar(50) NOT NULL COMMENT '标签名称',
  `slug` varchar(50) NOT NULL COMMENT 'URL 别名',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章标签表';

INSERT INTO `t_tag` (`id`, `name`, `slug`, `created_at`) VALUES
('4', 'Java', 'java', '2026-06-12 11:02:22');

CREATE TABLE `t_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID，自增主键',
  `username` varchar(50) NOT NULL COMMENT '登录用户名，唯一',
  `password` varchar(128) NOT NULL COMMENT '登录密码，MD5 加密存储',
  `nickname` varchar(50) DEFAULT '' COMMENT '用户昵称，用于前台展示',
  `email` varchar(100) DEFAULT '' COMMENT '电子邮箱',
  `avatar` varchar(500) DEFAULT '' COMMENT '头像 URL 地址',
  `bio` varchar(500) DEFAULT '' COMMENT '个人简介',
  `role` varchar(20) NOT NULL DEFAULT 'ROLE_USER' COMMENT '角色标识：ROLE_USER=普通用户，ROLE_ADMIN=管理员',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '账号状态：0=禁用，1=正常',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

INSERT INTO `t_user` (`id`, `username`, `password`, `nickname`, `email`, `avatar`, `bio`, `role`, `status`, `created_at`, `updated_at`) VALUES
('1', 'admin', '$2a$10$QaGywGtfVJHOvGDzUCMMPOow0J90BYyLFXqJdrgWGclvx8SLSDTDS', '超级管理员', 'admin@diamond.cn', '', '', 'ROLE_ADMIN', 1, '2026-06-11 12:12:45', '2026-06-11 23:35:19'),
('3', 'TestUser', '$2a$10$QaGywGtfVJHOvGDzUCMMPOow0J90BYyLFXqJdrgWGclvx8SLSDTDS', '路人甲', 'test@test.cn', 'https://b1og.oss-cn-beijing.aliyuncs.com/blog/2026/06/11/fc844fbc-a3b8-4f5d-a98b-073d7aa89a25.png', '没啥好说的，我只是个路人甲', 'ROLE_USER', 1, '2026-06-11 12:50:57', '2026-06-11 23:35:19');

SET FOREIGN_KEY_CHECKS = 1;
